//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task02.WeekDayConsoleClient.DayServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayServiceReference.IWeekDay")]
    public interface IWeekDay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeekDay/DayOfWeek", ReplyAction="http://tempuri.org/IWeekDay/DayOfWeekResponse")]
        string DayOfWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeekDay/DayOfWeek", ReplyAction="http://tempuri.org/IWeekDay/DayOfWeekResponse")]
        System.Threading.Tasks.Task<string> DayOfWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeekDayChannel : Task02.WeekDayConsoleClient.DayServiceReference.IWeekDay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeekDayClient : System.ServiceModel.ClientBase<Task02.WeekDayConsoleClient.DayServiceReference.IWeekDay>, Task02.WeekDayConsoleClient.DayServiceReference.IWeekDay {
        
        public WeekDayClient() {
        }
        
        public WeekDayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeekDayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeekDayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeekDayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DayOfWeek(System.DateTime date) {
            return base.Channel.DayOfWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> DayOfWeekAsync(System.DateTime date) {
            return base.Channel.DayOfWeekAsync(date);
        }
    }
}
